Repository cloudposse/terraform-aws-ec2-autoscale-group, pull requests merged in 2021-12, with the labels that each got.

#74 Added evaluation periods in description
  autoscaling.tf
Labels: patch

#79 feat: Parametrize `metadata_options.http_protocol_ipv6`
  README.md
  docs/terraform.md
  main.tf
  variables.tf
Labels: enhancement, no-release

#81 Fix: Remove Unused Providers
  README.md
  docs/terraform.md
  versions.tf
Labels: bugfix, no-release

#82 Chore: Run `make github/init`
  .github/auto-release.yml
  .github/workflows/auto-release.yml
Labels: patch, no-release
